services:
  frontend:
    image: ghcr.io/jorgecarleitao/stv-app-frontend:main
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"

  elections:
    image: ghcr.io/jorgecarleitao/stv-app@sha256:914d5b190b376493ce9c82064c82225b078eecea1f5f841b3880f5999d9bd963
    container_name: elections
    restart: unless-stopped
    user: "1000:1000"
    expose:
      - "8080"
    environment:
      RUST_LOG: info
    volumes:
      - elections-data:/app/data

  # https://caddyserver.com/docs/running#docker-compose
  proxy:
    image: docker.io/library/caddy:2
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - proxy-config:/config
      - proxy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      CADDY_EMAIL: ${ACME_CONTACT}

volumes:
  proxy-config:
  proxy-data:
  elections-data:
