services:
  frontend:
    image: ghcr.io/jorgecarleitao/stv-app-frontend@sha256:5596861c6e0b74bb097da0f3a686c3fb89538e9a060614e16b66c4701a250376
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"

  elections:
    image: ghcr.io/jorgecarleitao/stv-app@sha256:87f7cb4e3c0186c5d59ec7d3225738f7f4bffae95790bc0d4ee687b8724b7f45
    container_name: elections
    restart: unless-stopped
    user: "1000:1000"
    expose:
      - "8080"
    environment:
      RUST_LOG: info
    volumes:
      - elections-data:/app/data

  # https://caddyserver.com/docs/running#docker-compose
  proxy:
    image: docker.io/library/caddy:2
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - proxy-config:/config
      - proxy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      CADDY_EMAIL: ${ACME_CONTACT}

volumes:
  proxy-config:
  proxy-data:
  elections-data:
