services:
  frontend:
    image: ghcr.io/jorgecarleitao/stv-app-frontend@sha256:e25cb54e8eab17e682c40759b1e49ed6be123c1a1350474f394858381354407a
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"

  elections:
    image: ghcr.io/jorgecarleitao/stv-app@sha256:8037d41adfd9b23e6df0372eeb4bf25a13497630b347c3a156a7090ff27257d3
    container_name: elections
    restart: unless-stopped
    user: "1000:1000"
    expose:
      - "8080"
    environment:
      RUST_LOG: info
    volumes:
      - /mnt/volumes/elections-data:/app/data

  # https://caddyserver.com/docs/running#docker-compose
  proxy:
    image: docker.io/library/caddy:2
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - proxy-config:/config
      - proxy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      CADDY_EMAIL: ${ACME_CONTACT}

volumes:
  proxy-config:
  proxy-data:
