name: Prepare remote server
inputs:
  ssh_private_key:
    required: true
  ssh_ip:
    required: true

runs:
  using: composite
  steps:
    - name: Prepare SSH environment
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{inputs.ssh_private_key}}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        chmod 700 ~/.ssh

        # NOTE: this can be hardened via a TOFU approach, but for now we accept any host key
        ssh-keyscan -H ${{ inputs.ssh_ip }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Install Podman on remote
      shell: bash
      run: |
        ssh -i ~/.ssh/id_ed25519 root@${{ inputs.ssh_ip }} 'bash -s' << 'ENDSSH'
        set -e

        # Check if Podman is already installed
        if command -v podman &> /dev/null; then
          echo "Podman is already installed"
          podman --version
          exit 0
        fi

        echo "Installing Podman..."

        # Update package index
        apt-get update

        # Install Podman (available in Ubuntu 24.04 repos)
        apt-get install -y podman podman-compose

        # Enable rootless users to bind to privileged ports 80 and 443
        sysctl -w net.ipv4.ip_unprivileged_port_start=80
        echo "net.ipv4.ip_unprivileged_port_start=80" >> /etc/sysctl.conf

        echo "Podman installation complete"
        podman --version
        ENDSSH
        echo "Podman remote connection established"
